const WEATHER_FOR_WEEK = [
  {
    id: 1,
    date: "21/02/2022",
    temperatureMin: "+2",
    temperatureMax: "+7",
    atmPressure: "740",
    humidity: "85",
    wind: "2.7",
    description: "ясно",
    img_url: "./img/clear.png",
  },
  {
    id: 2,
    date: "22/02/2022",
    temperatureMin: "+3°",
    temperatureMax: "+6°",
    atmPressure: "735",
    humidity: "95",
    wind: "2.4",
    description: "облачно",
    img_url: "./img/cloudy.png",
  },
  {
    id: 3,
    date: "23/02/2022",
    temperatureMin: "0°",
    temperatureMax: "+2°",
    atmPressure: "740",
    humidity: "80",
    wind: "2.9",
    description: "облачно",
    img_url: "./img/some-clouds.png",
  },
  {
    id: 4,
    date: "24/02/2022",
    temperatureMin: "-2°",
    temperatureMax: "+3°",
    atmPressure: "754",
    humidity: "55",
    wind: "4.0",
    description: "дождь",
    img_url: "./img/rain.png",
  },
  {
    id: 5,
    date: "25/02/2022",
    temperatureMin: "-1°",
    temperatureMax: "+1°",
    atmPressure: "755",
    humidity: "60",
    wind: "2.0",
    description: "ясно, временами снег",
    img_url: "./img/sun-snow.png",
  },
  {
    id: 6,
    date: "26/02/2022",
    temperatureMin: "-4°",
    temperatureMax: "+2°",
    atmPressure: "754",
    humidity: "50",
    wind: "1.6",
    description: "облачно",
    img_url: "./img/some-clouds-2.png",
  },
  {
    id: 7,
    date: "27/02/2022",
    temperatureMin: "-2°",
    temperatureMax: "+3°",
    atmPressure: "750",
    humidity: "62",
    wind: "2.0",
    description: "снег",
    img_url: "./img/snow.png",
  },
];

export default WEATHER_FOR_WEEK;
